import pymongo
from bson import ObjectId  # Import the ObjectId class

# Replace these values with your actual MongoDB connection details
mongo_client = pymongo.MongoClient("mongodb://127.0.0.1:27017")

# Access or create a database (replace 'your_database' with your actual database name)
db = mongo_client["ProjectDB"]

# Access or create a collection within the database (replace 'your_collection' with your actual collection name)
collection = db["playersCollection"]

# Your dataset with custom _id field

player_data = [
    {
        "_id" : ObjectId(),
        "Team": "1s",
        "Name": "David Murphy",
        "Age": 41,
        "POS": "GK",
        "App": 1,
        "Goal Involvements": 0,
        "Clean Sheets": 0,
        "Yellows": 0,
        "Reds": 0,
        "Mins": 90
    },
    {
        "_id" : ObjectId(),
        "Team": "1s",
        "Name": "Carter Watt",
        "Age": 21,
        "POS": "GK",
        "App": 4,
        "Goal Involvements": 0,
        "Clean Sheets": 1,
        "Yellows": 0,
        "Reds": 0,
        "Mins": 360
    },
    {
        "_id" : ObjectId(),
        "Team": "1s",
        "Name": "Jonathan Tate",
        "Age": 40,
        "POS": "GK",
        "App": 3,
        "Goal Involvements": 0,
        "Clean Sheets": 1,
        "Yellows": 0,
        "Reds": 0,
        "Mins": 270
    },
    {
        "_id" : ObjectId(),
        "Team": "2s",
        "Name": "Ross Adair",
        "Age": 30,
        "POS": "GK",
        "App": 3,
        "Goal Involvements": 0,
        "Clean Sheets": 0,
        "Yellows": 0,
        "Reds": 0,
        "Mins": 270
    },
    {
        "_id" : ObjectId(),
        "Team": "1s",
        "Name": "Miguel Conceicao",
        "Age": 40,
        "POS": "GK",
        "App": 4,
        "Goal Involvements": 0,
        "Clean Sheets": 0,
        "Yellows": 1,
        "Reds": 0,
        "Mins": 360
    },
    {
        "_id" : ObjectId(),
        "Team": "2s",
        "Name": "Darren McMullan",
        "Age": 32,
        "POS": "GK",
        "App": 1,
        "Goal Involvements": 0,
        "Clean Sheets": 0,
        "Yellows": 0,
        "Reds": 0,
        "Mins": 90
    },
    {
        "_id" : ObjectId(),
        "Team": "1s",
        "Name": "Carl O'Neill",
        "Age": 34,
        "POS": "GK",
        "App": 1,
        "Goal Involvements": 0,
        "Clean Sheets": 0,
        "Yellows": 0,
        "Reds": 0,
        "Mins": 90
    },
    {
        "_id" : ObjectId(),
        "Team": "2s",
        "Name": "Paul Devlin",
        "Age": 33,
        "POS": "GK",
        "App": 0,
        "Goal Involvements": 0,
        "Clean Sheets": 0,
        "Yellows": 0,
        "Reds": 0,
        "Mins": 0
    },
    {
        "_id" : ObjectId(),
        "Team": "2s",
        "Name": "Jamie Gent",
        "Age": "",
        "POS": "GK",
        "App": 2,
        "Goal Involvements": 0,
        "Clean Sheets": 0,
        "Yellows": 1,
        "Reds": 1,
        "Mins": 140
    },
    {
        "_id" : ObjectId(),
        "Team": "1s",
        "Name": "Jordan Mills",
        "Age": 33,
        "POS": "DEF",
        "App": 14,
        "Goal Involvements": 0,
        "Clean Sheets": 2,
        "Yellows": 0,
        "Reds": 0,
        "Mins": 1214
    },
    {
        "_id" : ObjectId(),
        "Team": "1s",
        "Name": "Kyle Moore",
        "Age": 22,
        "POS": "DEF",
        "App": 13,
        "Goal Involvements": 0,
        "Clean Sheets": 2,
        "Yellows": 0,
        "Reds": 0,
        "Mins": 682
    },
    {
        "_id" : ObjectId(),
        "Team": "1s",
        "Name": "Nathan Crawford",
        "Age": 29,
        "POS": "DEF",
        "App": 14,
        "Goal Involvements": 0,
        "Clean Sheets": 2,
        "Yellows": 1,
        "Reds": 0,
        "Mins": 1125
    },
    {
        "_id" : ObjectId(),
        "Team": "2s",
        "Name": "Karl Johnston",
        "Age": 40,
        "POS": "DEF",
        "App": 9,
        "Goal Involvements": 0,
        "Clean Sheets": 1,
        "Yellows": 1,
        "Reds": 0,
        "Mins": 723
    },
    {
        "_id" : ObjectId(),
        "Team": "1s",
        "Name": "Michael Keable",
        "Age": 31,
        "POS": "DEF",
        "App": 12,
        "Goal Involvements": 0,
        "Clean Sheets": 2,
        "Yellows": 3,
        "Reds": 0,
        "Mins": 1001
    },
    {
        "_id" : ObjectId(),
        "Team": "",
        "Name": "Craig McCullough",
        "Age": 37,
        "POS": "DEF",
        "App": 4,
        "Goal Involvements": 0,
        "Clean Sheets": 0,
        "Yellows": 0,
        "Reds": 0,
        "Mins": 360
    },
    {
        "_id" : ObjectId(),
        "Team": "2s",
        "Name": "Danny Smyth",
        "Age": 30,
        "POS": "DEF",
        "App": 1,
        "Goal Involvements": 0,
        "Clean Sheets": 0,
        "Yellows": 0,
        "Reds": 0,
        "Mins": 24
    },
    {
        "_id" : ObjectId(),
        "Team": "2s",
        "Name": "Michael Massey",
        "Age": 38,
        "POS": "DEF",
        "App": 6,
        "Goal Involvements": 0,
        "Clean Sheets": 0,
        "Yellows": 2,
        "Reds": 2,
        "Mins": 266
    },
    {
        "_id" : ObjectId(),
        "Team": "1s",
        "Name": "Nathan Shaw",
        "Age": 32,
        "POS": "DEF",
        "App": 8,
        "Goal Involvements": 0,
        "Clean Sheets": 0,
        "Yellows": 1,
        "Reds": 0,
        "Mins": 518
    },
    {
        "Team": "1s",
        "Name": "Kurtis Mcclure",
        "Age": 27,
        "POS": "MID",
        "App": 14,
        "Goal Involvements": 6,
        "Clean Sheets": 1,
        "Yellows": 1,
        "Reds": 0,
        "Mins": 843
    },
    {
        "Team": "2s",
        "Name": "Reece Beattie",
        "Age": 21,
        "POS": "MID",
        "App": 6,
        "Goal Involvements": 1,
        "Clean Sheets": 0,
        "Yellows": 1,
        "Reds": 0,
        "Mins": 452
    },
    {
        "Team": "1s",
        "Name": "Michael Bell",
        "Age": 38,
        "POS": "MID",
        "App": 11,
        "Goal Involvements": 2,
        "Clean Sheets": 1,
        "Yellows": 2,
        "Reds": 0,
        "Mins": 839
    },
    {
        "Team": "2s",
        "Name": "Graham Crawford",
        "Age": 33,
        "POS": "MID",
        "App": 7,
        "Goal Involvements": 1,
        "Clean Sheets": 0,
        "Yellows": 1,
        "Reds": 0,
        "Mins": 508
    },
    {
        "Team": "2s",
        "Name": "Dean Davidson",
        "Age": 26,
        "POS": "MID",
        "App": 5,
        "Goal Involvements": 0,
        "Clean Sheets": 0,
        "Yellows": 0,
        "Reds": 0,
        "Mins": 223
    },
    {
        "Team": "2s",
        "Name": "Daniel Edgeworth",
        "Age": 31,
        "POS": "MID",
        "App": 6,
        "Goal Involvements": 5,
        "Clean Sheets": 0,
        "Yellows": 0,
        "Reds": 0,
        "Mins": 483
    },
    {
        "Team": "2s",
        "Name": "Francis Feeney",
        "Age": 39,
        "POS": "MID",
        "App": 9,
        "Goal Involvements": 2,
        "Clean Sheets": 0,
        "Yellows": 0,
        "Reds": 0,
        "Mins": 783
    },
    {
        "Team": "2s",
        "Name": "Jason Ritchie",
        "Age": 36,
        "POS": "MID",
        "App": 13,
        "Goal Involvements": 2,
        "Clean Sheets": 0,
        "Yellows": 2,
        "Reds": 0,
        "Mins": 1150
    },
    {
        "Team": "2s",
        "Name": "Ben Hawthorne",
        "Age": 20,
        "POS": "MID",
        "App": 10,
        "Goal Involvements": 0,
        "Clean Sheets": 0,
        "Yellows": 0,
        "Reds": 0,
        "Mins": 587
    },
    {
        "Team": "2s",
        "Name": "Reece Thompson",
        "Age": 26,
        "POS": "MID",
        "App": 6,
        "Goal Involvements": 0,
        "Clean Sheets": 0,
        "Yellows": 0,
        "Reds": 1,
        "Mins": 402
    },
    {
        "Team": "1s",
        "Name": "Michael McBride",
        "Age": 28,
        "POS": "MID",
        "App": 4,
        "Goal Involvements": 3,
        "Clean Sheets": 0,
        "Yellows": 0,
        "Reds": 0,
        "Mins": 296
    },
    {
        "Team": "1s",
        "Name": "James Smith",
        "Age": 33,
        "POS": "MID",
        "App": 10,
        "Goal Involvements": 3,
        "Clean Sheets": 1,
        "Yellows": 3,
        "Reds": 0,
        "Mins": 900
    },
    {
        "Team": "2s",
        "Name": "Ross Young",
        "Age": 27,
        "POS": "MID",
        "App": 6,
        "Goal Involvements": 1,
        "Clean Sheets": 0,
        "Yellows": 2,
        "Reds": 1,
        "Mins": 279
    },
    {
        "Team": "2s",
        "Name": "Ross Waide",
        "Age": 21,
        "POS": "MID",
        "App": 6,
        "Goal Involvements": 0,
        "Clean Sheets": 0,
        "Yellows": 1,
        "Reds": 0,
        "Mins": 525
    },
    {
        "Team": "2s",
        "Name": "Reece Dylan Atkinson",
        "Age": 25,
        "POS": "MID",
        "App": 1,
        "Goal Involvements": 0,
        "Clean Sheets": 0,
        "Yellows": 0,
        "Reds": 0,
        "Mins": 0
    },
    {
        "Team": "2s",
        "Name": "David Brotherston",
        "Age": 36,
        "POS": "MID",
        "App": 1,
        "Goal Involvements": 0,
        "Clean Sheets": 0,
        "Yellows": 1,
        "Reds": 0,
        "Mins": 90
    },
    {
        "Team": "2s",
        "Name": "Thomas Dorrian",
        "Age": 32,
        "POS": "MID",
        "App": 1,
        "Goal Involvements": 0,
        "Clean Sheets": 0,
        "Yellows": 0,
        "Reds": 0,
        "Mins": 9
    },
    {
        "Team": "2s",
        "Name": "Dean Proctor",
        "Age": 30,
        "POS": "MID",
        "App": 3,
        "Goal Involvements": 0,
        "Clean Sheets": 0,
        "Yellows": 1,
        "Reds": 0,
        "Mins": 174
    },
    {
        "Team": "2s",
        "Name": "Matthew Hall",
        "Age": 28,
        "POS": "MID",
        "App": 4,
        "Goal Involvements": 3,
        "Clean Sheets": 0,
        "Yellows": 0,
        "Reds": 0,
        "Mins": 360
    },
    {
        "Team": "2s",
        "Name": "Matthew Palmer",
        "Age": 27,
        "POS": "MID",
        "App": 1,
        "Goal Involvements": 0,
        "Clean Sheets": 0,
        "Yellows": 0,
        "Reds": 0,
        "Mins": 10
    },
    {
        "Team": "1s",
        "Name": "Nathan Cousins",
        "Age": 22,
        "POS": "ATK",
        "App": 14,
        "Goal Involvements": 12,
        "Clean Sheets": 1,
        "Yellows": 4,
        "Reds": 0,
        "Mins": 945
    },
    {
        "Team": "2s",
        "Name": "Craig Edwards",
        "Age": 39,
        "POS": "ATK",
        "App": 13,
        "Goal Involvements": 0,
        "Clean Sheets": 0,
        "Yellows": 5,
        "Reds": 1,
        "Mins": 894
    },
    {
        "Team": "1s",
        "Name": "Curtis Houston",
        "Age": 20,
        "POS": "ATK",
        "App": 14,
        "Goal Involvements": 13,
        "Clean Sheets": 1,
        "Yellows": 2,
        "Reds": 0,
        "Mins": 1168
    },
    {
        "Team": "1s",
        "Name": "Adam Munn",
        "Age": 21,
        "POS": "ATK",
        "App": 5,
        "Goal Involvements": 3,
        "Clean Sheets": 1,
        "Yellows": 2,
        "Reds": 0,
        "Mins": 540
    },
    {
        "Team": "2s",
        "Name": "Michael McKeown",
        "Age": 37,
        "POS": "ATK",
        "App": 0,
        "Goal Involvements": 0,
        "Clean Sheets": 0,
        "Yellows": 0,
        "Reds": 0,
        "Mins": 0
    },
    {
        "Team": "2s",
        "Name": "Jack Bill",
        "Age": 20,
        "POS": "ATK",
        "App": 1,
        "Goal Involvements": 0,
        "Clean Sheets": 0,
        "Yellows": 0,
        "Reds": 0,
        "Mins": 90
    },
    {
        "Team": "2s",
        "Name": "Calvin Brotherston",
        "Age": 26,
        "POS": "ATK",
        "App": 2,
        "Goal Involvements": 0,
        "Clean Sheets": 0,
        "Yellows": 0,
        "Reds": 0,
        "Mins": 108
    },
    {
        "Team": "2s",
        "Name": "James Sproule",
        "Age": 37,
        "POS": "ATK",
        "App": 10,
        "Goal Involvements": 0,
        "Clean Sheets": 0,
        "Yellows": 3,
        "Reds": 1,
        "Mins": 809
    },
    {
        "Team": "2s",
        "Name": "Stephen Steele",
        "Age": 43,
        "POS": "ATK",
        "App": 2,
        "Goal Involvements": 2,
        "Clean Sheets": 0,
        "Yellows": 1,
        "Reds": 0,
        "Mins": 180
    },
    {
        "Team": "1s",
        "Name": "Jamie Wallace",
        "Age": 28,
        "POS": "ATK",
        "App": 2,
        "Goal Involvements": 0,
        "Clean Sheets": 0,
        "Yellows": 0,
        "Reds": 0,
        "Mins": 68
    },
    {
        "Team": "2s",
        "Name": "Daniel Orr",
        "Age": 32,
        "POS": "ATK",
        "App": 2,
        "Goal Involvements": 1,
        "Clean Sheets": 0,
        "Yellows": 0,
        "Reds": 0,
        "Mins": 180
    }
    
    ]
